alias grep="grep --color=auto"
alias ls="ls --color=auto"
alias cd..="cd .."		
alias s="cd .."
alias p="cd -"
alias du="du -sh"
alias df="df -h"
alias ll="ls -l"
alias la="ls -A"
alias s="cd .."
alias l="ls"
alias l1="ls -1"
